image: Ubuntu

stack: jdk 11

branches:
  only:
    - main

build: off

install:
  - chmod +x gradlew
  - java -jar ./jar_files/webdrivermanager-5.3.2.jar
  - java -jar ./artifacts/app-order.jar &

build_script:
  - ./gradlew test --info